sudo: false
dist: trusty
language: node_js
node_js:
- '6'
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
cache:
  directories:
    - node_modules
script:
    - npm test
    - npm run coverage
