sudo: false
dist: trusty
language: node_js
node_js:
- '8'
addons:
  firefox: latest
  chrome: stable
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
cache:
  directories:
    - node_modules
script:
    - npm test
    - npm run coverage
